subscribers:

  camera_topics: [
    "/stereo_center/left/image",
    "/stereo_zoom/left/image",
    "/stereo_center/right/image",
    "/stereo_zoom/right/image"
  ]

  camera_frame_ids: [
    "stereo_center_left",
    "stereo_zoom_left",
    "stereo_center_right",
    "stereo_zoom_right"
  ]

  queue_size: 1

publisher:

    topic: "/camera_signalman/image_raw"

    queue_size: 1